name: "🚀 功能请求"
description: "为项目建议一个新功能或改进"
title: "[Feature] <Topic>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "## 感谢您提出功能建议！\n请详细描述您的需求，帮助我们更好地理解。"

  - type: textarea
    id: problem
    attributes:
      label: "问题描述"
      description: "您希望解决什么问题？请描述您遇到的痛点或需求"
      placeholder: "例如：我经常需要...，但目前系统不支持..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "建议的解决方案"
      description: "清晰描述您希望实现的功能"
      placeholder: "我希望系统能够..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "考虑的替代方案"
      description: "您考虑过哪些替代方案？"

  - type: dropdown
    id: priority
    attributes:
      label: "对您的重要程度"
      description: "请选择这个功能对您的重要程度"
      options:
        - "非常重要 - 没有这个功能我很难使用"
        - "重要 - 能显著改善使用体验"
        - "一般 - 有的话会更好"
        - "较低 - 只是一个想法"

  - type: checkboxes
    id: terms
    attributes:
      label: "确认事项"
      description: "请确认以下事项"
      options:
        - label: "我已搜索过现有Issue，没有找到相同建议"
          required: true
        - label: "我同意遵守此项目的行为准则"
          required: true